### ISSUE TITLE
无法打开源文件 "leetcode-entry.h"

### ISSUE THREAD

**Issue by plokid** [xavier-cai/vscode-leetcode-cpp-debug#10]
linux系统，gcc编译器
![2021-03-29_10-38](https://user-images.githubusercontent.com/72876162/112780338-38028b00-907b-11eb-9133-86e07aee0499.png)
这个头文件从哪来的?

**Comment by xavier-cai** [comment]
包括`leetcode-entry.h`和`leetcode-main.cpp`在内的临时文件均是在运行时从资源文件夹([link](https://github.com/xavier-cai/vscode-leetcode-cpp-debug/tree/master/resources/code/cpp))拷贝而来

**Comment by plokid** [comment]
开始DEBUG后，文件夹内出现“leetcode-main.cpp”在内的临时文件，随后立即删除，没有弹出终端。

**Comment by xavier-cai** [comment]
无法弹出终端这种情况一般来说是debugging配置本身的问题导致的，可尝试如下步骤来解决问题：
- 将插件的设置项 `Delete Temporary Contents`设为false来保存插件生成的临时文件
- 运行插件提供的debug命令来启动debug过程并生成所需文件
- 以 `leetcode-main.cpp` 作为入口文件手动开始debug以排除插件干扰
- 如果排除插件干扰的情况下能顺利启动终端来debug，欢迎留言继续解决问题

**Comment by plokid** [comment]
![2021-04-02_19-43](https://user-images.githubusercontent.com/72876162/113412779-b8aee780-93eb-11eb-8897-1a4cf7e7cbe3.png)

**Comment by plokid** [comment]
linux下好像不支持direct.h

**Comment by xavier-cai** [comment]
感谢提供线索！该问题已由贡献者[@zhongluqiang](https://github.com/zhongluqiang)修复：[PR](https://github.com/xavier-cai/vscode-leetcode-cpp-debug/pull/8)
现已更新至marketplace，因此更新至v0.0.7版本应该就能解决这个问题了
