### ISSUE TITLE
debug无法自动运行

### ISSUE THREAD

**Issue by plokid** [xavier-cai/vscode-leetcode-cpp-debug#12]
debug程序不能自动运行
但我可以保存临时文件，并运行"leetcode-main.cpp"
linux系统

**Comment by plokid** [comment]
而且这么做无法设置断点

**Comment by xavier-cai** [comment]
通过`leetcode-main.cpp`作为入口无法正常启动调试，这说明应该是调试环境本身有问题，与插件无关

问题描述看起来有可能是中文文件名导致的问题，请参考[Issue#9](https://github.com/xavier-cai/vscode-leetcode-cpp-debug/issues/9)

**Comment by plokid** [comment]
问题已解决，可以从leetcode-main.cpp进入调试，但无法自动启动
个人认为是终端启动问题，建议改为vscode内置终端

**Comment by xavier-cai** [comment]
实际上，插件并不会自动配置和修改任何调试配置，只是负责启动已经配置好的调试任务，这意味着只要你的配置是从vscode内置终端启动调试就行了
