### ISSUE TITLE
无法调试solution这个类

### ISSUE THREAD

**Issue by sjtuwater** [xavier-cai/vscode-leetcode-cpp-debug#17]
如题，在进行debug时，无法调试solution这里面的代码，他会说moudule not obtained

**Comment by xavier-cai** [comment]
我没有遇到过类似问题，麻烦详细描述一下问题发生的情况，比如“他会说moudule not obtained”里面的“他”是谁？是vscode弹出的提示窗抑或是使用的编译器提示的编译错误？最好能附上详细的错误内容或截图

**Comment by sjtuwater** [comment]
刚才我改了一下windows 的默认编码为UTF8，可以调试了，我大概明白应该是windows的文件名默认编码为GBK，导致调试的时候不能获取这个文件（中文leetcode的文件名为中文题目，头文件里面加入了中文名字，g++编译的 时候显示错误有时候会是乱码的），晚点我把windows默认编码改回去给你截图

**Comment by sjtuwater** [comment]
刚才在看关闭的议题时，看到了和我说的类似的问题，这个现在我已经解决了，方法是将windows的默认编码改为utf8编码就行，然后vscode里面的题目以及调试相关的代码编码都设置为utf8，个人认为时gdb不识别windows默认文件名为GBK编码的中文文件名，或者加载进去的文件名被强转为utf8后乱码，无法识别源文件导致无法调试
![解决](https://user-images.githubusercontent.com/61745138/133872435-753ad561-10dd-458b-b349-a06d533b4371.gif)

**Comment by xavier-cai** [comment]
看起来你这种是另外一种可行的方法，此外也可以尝试一下[插件设置](https://github.com/xavier-cai/vscode-leetcode-cpp-debug/blob/master/README_zh-CN.md#%E6%8F%92%E4%BB%B6%E8%AE%BE%E7%BD%AE)里面的`Output File Encoding`是否能解决问题

**Comment by sjtuwater** [comment]
在设置里面可以设置的，但是无法根源性的解决这个问题，之前我就是通过插件设置里面设置的，但是powershell或是gdb依然会将GBK编码的文件名强转为utf8（然后乱码），这样就会导致编译之后调试找不到源文件（因为源文件的名字已经被强转为utf8编码乱码了，所以会提示module not oobtained）
