### ISSUE TITLE
调试时设置断点失效

### ISSUE THREAD

**Issue by huangluzhi** [xavier-cai/vscode-leetcode-cpp-debug#9]
您好，按照说明运行LeetCode C++ Debugger: Start Debugging断点变成圆圈并提示module containing this breakpoint has not yet loaded or the breakpoint address could not be obtained，无法单步调试，但是终端有响应并能正常输入输出。
此情况仅在使用插件调试时出现，在自己的leetcode无关的工程调试中则正常。
![image](https://user-images.githubusercontent.com/26925790/103306079-af5a5b80-4a47-11eb-951d-2a6d8aa84e29.png)

**Comment by xavier-cai** [comment]
**可能的原因：**
您的lc和其他工程使用了不同的vscode(调试)配置

**解决方案：**
- 将插件LeetCode C++ Debugger的设置项`Delete Temporary Contents`值置为`false`
- 运行`LeetCode C++ Debugger: Start Debugging`生成并保留临时代码文件(`leetcode-main.cpp`等文件)
- 使用`leetcode-main.cpp`作为程序入口手动启动调试过程排除插件干扰
- 如果排除插件干扰后发现可以正常调试，而通过插件启动调试则无法正常调试，请贴出您使用的调试环境和配置

**Comment by huangluzhi** [comment]
![image](https://user-images.githubusercontent.com/26925790/103330254-95e2ff00-4a9b-11eb-8e01-9e6064cc68ab.png)
如图，排除插件干扰后可以正常调试，通过插件启动无法正常调试。
我的环境及配置为
OS: Win10 x64 Professional
编译器: MinGW g++.exe
.vscode文件夹内配置：
launch.json
`// https://code.visualstudio.com/docs/cpp/launch-json-reference
{
    "version": "0.2.0",
    "configurations": [{
        "name": "(gdb) Launch", // 配置名称，将会在启动配置的下拉菜单中显示
        "type": "cppdbg", // 配置类型，cppdbg对应cpptools提供的调试功能；可以认为此处只能是cppdbg
        "request": "launch", // 请求配置类型，可以为launch（启动）或attach（附加）
        "program": "${fileDirname}/${fileBasenameNoExtension}.exe", // 将要进行调试的程序的路径
        "args": ["-g",], // 程序调试时传递给程序的命令行参数，一般设为空即可
        "stopAtEntry": false, // 设为true时程序将暂停在程序入口处，相当于在main上打断点
        "cwd": "${workspaceFolder}", // 调试程序时的工作目录，此为工作区文件夹；改成${fileDirname}可变为文件所在目录
        "environment": [], // 环境变量
        "externalConsole": false, // 使用单独的cmd窗口，与其它IDE一致；为false时使用内置终端
        "internalConsoleOptions": "neverOpen", // 如果不设为neverOpen，调试时会跳到“调试控制台”选项卡，你应该不需要对gdb手动输命令吧？
        "MIMode": "gdb", // 指定连接的调试器，可以为gdb或lldb。但我没试过lldb
        "miDebuggerPath": "gdb.exe", // 调试器路径，Windows下后缀不能省略，Linux下则不要
        "setupCommands": [
            { // 模板自带，好像可以更好地显示STL容器的内容，具体作用自行Google
                "description": "Enable pretty-printing for gdb",
                "text": "-enable-pretty-printing",
                "ignoreFailures": false
            }
        ],
        "preLaunchTask": "Compile" // 调试会话开始前执行的任务，一般为编译程序。与tasks.json的label相对应
    }]
}
`

tasks.json
`// https://code.visualstudio.com/docs/editor/tasks
{
    "version": "2.0.0",
    "tasks": [{
        "label": "Compile", // 任务名称，与launch.json的preLaunchTask相对应
        "command": "g++",   // 要使用的编译器，C++用g++
        "args": [
            "${file}",
            "-o",    // 指定输出文件名，不加该参数则默认输出a.exe，Linux下默认a.out
            "${fileDirname}/${fileBasenameNoExtension}.exe",
            "-g",    // 生成和调试有关的信息
            "-m64", // 不知为何有时会生成16位应用而无法运行，加上此条可强制生成64位的
            "-Wall", // 开启额外警告
            "-static-libgcc",     // 静态链接libgcc，一般都会加上
            "-fexec-charset=GBK", // 生成的程序使用GBK编码，不加这条会导致Win下输出中文乱码；繁体系统改成BIG5
            // "-std=c11", // 要用的语言标准，根据自己的需要修改。c++可用c++14
        ], // 编译的命令，其实相当于VSC帮你在终端中输了这些东西
        "type": "process", // process是把预定义变量和转义解析后直接全部传给command；shell相当于先打开shell再输入命令，所以args还会经过shell再解析一遍
        "group": {
            "kind": "build",
            "isDefault": true // 不为true时ctrl shift B就要手动选择了
        },
        "presentation": {
            "echo": true,
            "reveal": "always", // 执行任务时是否跳转到终端面板，可以为always，silent，never。具体参见VSC的文档
            "focus": false,     // 设为true后可以使执行task时焦点聚集在终端，但对编译C/C++来说，设为true没有意义
            "panel": "shared"   // 不同的文件的编译信息共享一个终端面板
        },
        "problemMatcher":"$gcc" // 捕捉编译时终端里的报错信息到问题面板中，修改代码后需要重新编译才会再次触发
        // 本来有Lint，再开problemMatcher就有双重报错，但MinGW的Lint效果实在太差了；用Clang可以注释掉
    }]
}`

settings.json
`{
    "files.defaultLanguage": "c", // ctrl+N新建文件后默认的语言
    "editor.formatOnType": true,  // 输入分号(C/C++的语句结束标识)后自动格式化当前这一行的代码
    "editor.suggest.snippetsPreventQuickSuggestions": false, // clangd的snippets有很多的跳转点，不用这个就必须手动触发Intellisense了
    "editor.acceptSuggestionOnEnter": "off", // 我个人的习惯，按回车时一定是真正的换行，只有tab才会接受Intellisense
    // "editor.snippetSuggestions": "top", // （可选）snippets显示在补全列表顶端，默认是inline

    "code-runner.runInTerminal": true, // 设置成false会在“输出”中输出，无法输入
    "code-runner.executorMap": {
        "c": "gcc '$fileName' -o '$fileNameWithoutExt.exe' -Wall -O2 -m64 -lm -static-libgcc -std=c11 -fexec-charset=GBK && &'./$fileNameWithoutExt.exe'",
        "cpp": "g++ '$fileName' -o '$fileNameWithoutExt.exe' -Wall -O2 -m64 -static-libgcc -std=c++14 -fexec-charset=GBK && &'./$fileNameWithoutExt.exe'"
        // "c": "gcc $fileName -o $fileNameWithoutExt.exe -Wall -O2 -m64 -lm -static-libgcc -std=c11 -fexec-charset=GBK && $dir$fileNameWithoutExt.exe",
        // "cpp": "g++ $fileName -o $fileNameWithoutExt.exe -Wall -O2 -m64 -static-libgcc -std=c++14 -fexec-charset=GBK && $dir$fileNameWithoutExt.exe"
    }, // 右键run code时运行的命令；未注释的仅适用于PowerShell（Win10默认）和pwsh，文件名中有空格也可以编译运行；注释掉的适用于cmd（win7默认）、PS和bash，但文件名中有空格时无法运行
    "code-runner.saveFileBeforeRun": true, // run code前保存
    "code-runner.preserveFocus": true,     // 若为false，run code后光标会聚焦到终端上。如果需要频繁输入数据可设为false
    "code-runner.clearPreviousOutput": false, // 每次run code前清空属于code runner的终端消息，默认false
    "code-runner.ignoreSelection": true,   // 默认为false，效果是鼠标选中一块代码后可以单独执行，但C是编译型语言，不适合这样用
    "code-runner.fileDirectoryAsCwd": true, // 将code runner终端的工作目录切换到文件目录再运行，对依赖cwd的程序产生影响；如果为false，executorMap要加cd $dir

    "C_Cpp.clang_format_sortIncludes": true,
    "files.associations": {
        "algorithm": "cpp",
        "bitset": "cpp",
        "chrono": "cpp",
        "iterator": "cpp",
        "xhash": "cpp",
        "xtree": "cpp",
        "xutility": "cpp",
        "deque": "cpp",
        "list": "cpp",
        "vector": "cpp",
        "xstring": "cpp"
    }, // 格式化时调整include的顺序（按字母排序）
}`

**Comment by xavier-cai** [comment]
很遗憾使用您提供的配置文件无法复现该问题，可能需要您自行对比两种运行条件下的DEBUG CONSOLE的输出内容来发现问题，欢迎您贴出您发现的内容来做进一步的讨论。

**Comment by huangluzhi** [comment]
以插件作为入口调试，发现断点仅在class Solution所在的cpp文件里失效，并且单步调试进入文件时会报错。以main.cpp为入口调试同样在答题的cpp内断点失效。
![image](https://user-images.githubusercontent.com/26925790/103372041-f27e0280-4b0b-11eb-938e-271872959cc7.png)
通过搜索得知MinGW的gdb调试不支持中文路径，而本身文件名又默认包含中文（中文leetcode站），因此我推断应该是文件包含中文路径的问题。请问这种情况除了换调试器还有其他方法吗，如果没有的话请问能推荐合适的调试器吗？

**Comment by xavier-cai** [comment]
**解决方案如下：**
**方案1** 更改文件命使其不包含中文：
找到`LeetCode`插件名为`File Path`的设置项，点击`Edit in setting.json`，添加如下内容即可将文件名修改为如1.cpp的形式：
```
"leetcode.filePath": {
    "default": {
        "filename": "${id}.${ext}",
        "folder": ""
    }
} 
```
**方案2** 使用支持中文路径的编译/调试工具如clang/lldb

**Comment by huangluzhi** [comment]
感谢解答
